### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gneworld** [Ekleog/wasmtime-async#1]
@Ekleog Hello, firstly  thanks much for your great work about this.
when I try to run the example code with wasmtime 0.39.1, I got many build errors like this, seems that wasmtime 0.16 has much differences with 0.39, I am new to rust, so how to fix this build errors with recent wasmtime? thanks much!
![image](https://user-images.githubusercontent.com/30924021/191017012-ba24ec82-172d-4a55-92b1-f78c7f3f9219.png)

**Comment by Ekleog** [comment]
You're definitely right, this crate has not been kept up-to-date! But the good news is, recent versions of wasmtime (including 0.39, AFAIR) already include the features this crate was meant for providing, so you should just not need this crate and everything is already upstream :)

Actually that makes me think I should archive this repo, thank you!

**Comment by Ekleog** [comment]
(For more information, you can look at places like https://docs.rs/wasmtime/1.0.0/wasmtime/struct.Func.html#method.new_async )

**Comment by gneworld** [comment]
@Ekleog Thanks much for your advice!
